server:
  port: 8762
spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignoredServices: '*'
  routes:
    dependente:
      path: /dependente-api/**
      serviceId: DEPENDENTE-API
    ferias:
      path: /ferias-api/**
      serviceId: FERIAS-API
    servidor:
      path: /servidor-api/**
      serviceId: SERVIDOR-API
    unidade:
      path: /unidade-api/**
      serviceId: UNIDADE-API
    comissionamento:
      path: /comissionamento-api/**
      serviceId: COMISSIONAMENTO-API
hystrix: 
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
